const AllImages = {
    mainLogo: "/media/images/ftvlogorealwhite.png",
    DarkLogo: "/media/images/ftvlogorealblack.png",
    DarkLogo2: "/media/images/logo55.png",
    malaika: "/media/images/malaika.png",
    uprightarrow: "/media/images/up-right-arrow.png",
    uprightarroww: "/media/images/up-right-arrow-w.png",
    LoaderImg: "/media/images/loader.gif",
    bannerVideo3: "/media/videos/HomePage-V1-3.mp4",
    bannerVideomob23: "/media/videos/HomePage-V2-3.mp4",
    homeBanner: "/media/images/Home-banner.webp",
    realesateBanner: "/media/images/realesate-banner.webp",
    fdimondcrown:"/media/images/fdimond-crw.png",
    fdimondcr:"/media/images/fdimond-cr.png",
    fdimondcrown2:"/media/images/f-common.png",
    flongnew:"/media/images/flongnew.png",
    intro1: "/media/images/intro-1.webp",
    intro2: "/media/images/intro-2.webp",
    features1: "/media/images/Brand-Steeped.webp",
    features2: "/media/images/world-class-standards.jpg",
    features3: "/media/images/absolute-brand-support.jpg",
    features4: "/media/images/assured-brand-loyalty.jpg",
    features5: "/media/images/profetional-web.webp",
    features6: "/media/images/extensive-digital-marketing.webp",
    features7: "/media/images/designing-assistance.jpg",
    featuresIcon1: "/media/images/brand-steeped.png",
    featuresIcon2: "/media/images/investment-potential.png",
    featuresIcon3: "/media/images/neighborhood-harmony.png",
    featuresIcon4: "/media/images/unwavering-quest.png",
    featuresIcon5: "/media/images/upscale-living.png",
    // luxuryBanner: "/media/images/luxury-banner.png",
    BrandLogo: "/media/images/brand-logo-usage.png",
    communitySupport: "/media/images/community-support.png",
    designingAssitance: "/media/images/designing-assisstance.png",
    digitalMarketing: "/media/images/digital-marketing.png",
    PerIntegration: "/media/images/integration.png",
    fConnect: "/media/images/f-connect.png",
    support: "/media/images/360-support.png",
    beThePartImg: "/media/images/be-the-part-img.webp",
    luxuryDesktopVideo: "/media/videos/HomePage-V1-4.mp4",
    homepageSVideo: "/media/videos/home-page-secondary.mp4",
    ftvVideo: "/media/videos/real-estate-photo-slide.mp4",
    ftvVideoMob: "/media/videos/real-estate-photo-slide-mod.mp4",
    michalvideo: "/media/videos/michelvideos.mp4",
    luxuryMobVideo: "/media/videos/HomePage-V2-4.mp4", 
    kkvideos: "/media/videos/kkvideos.mp4",
    newsBanner: "/media/images/news-banner.jpg",
    // future1: "/media/images/future-1.webp",
    // future2: "/media/images/future-2.webp",
    // future3: "/media/images/future-3.webp",
    // future4: "/media/images/future-4.webp",
    fBranding : "/media/images/f-brand.png",
    ftvBanner : "/media/images/about_us-banner.webp",
    abooutImg1 : "/media/images/about-intro1.webp",
    abooutImg2 : "/media/images/about-intro2.webp",
    maImg1 : "/media/images/ma-1.webp",
    kkImg1 : "/media/images/kk-1.jpg",
    projectBanner : "/media/images/project-banner.webp",
    // residenceBanner : "/media/images/residence-img1.webp",
    contactBanner : "/media/images/contact-banner.png",
    faqBanner : "/media/images/faq-banner.webp",
    blogBanner : "/media/images/blog-banner.webp",
    fashiontvimg : "/media/images/fashiontv.png",
    contactImg : "/media/images/contact-img.png",
    realIntro : "/media/images/real-intro.png",
    ftvWord : "/media/images/ftv-word.png",
    categoriesImg1 : "/media/images/categories/business-bay.webp",
    categoriesImg2 : "/media/images/categories/co-works.webp",
    categoriesImg3 : "/media/images/categories/furnished-apartments.webp",
    categoriesImg4 : "/media/images/categories/hotels.webp",
    categoriesImg5 : "/media/images/categories/house.webp",
    categoriesImg6 : "/media/images/categories/malls.webp",
    categoriesImg7 : "/media/images/categories/outlet-malls.webp",
    categoriesImg8 : "/media/images/categories/residences.webp",
    categoriesImg9 : "/media/images/categories/resorts.webp",
    categoriesImg10 : "/media/images/categories/villas.webp",
    ProjectsBalewadi : "/media/images/projects/balewadi.webp",
    ProjectMohali : "/media/images/ftowers.jpg",
    ProjectfTower : "/media/images/projects/ftowers.jpg",
    ProjectsDubai : "/media/images/projects/dubai.webp",
    ProjectsFcrown : "/media/images/projects/f-crown.webp",
    ProjectsGhatkopar : "/media/images/projects/ghatkopar.webp",
    ProjectsHyderabad : "/media/images/projects/hyderabad.webp",
    ProjectskalyaniNagar : "/media/images/projects/kalyani_nagar.webp",
    ProjectslLudhiana : "/media/images/projects/ludhiana.jpg",
    ProjectsMalad : "/media/images/projects/malad.webp",
    ProjectsNoida : "/media/images/projects/fpre.webp",
    ProjectsPoland : "/media/images/projects/polland-f-house.jpg",
    ProjectsHotelsBali : "/media/images/projects/f-hotels-bali.jpg",
    ProjectsRanchiUpComing : "/media/images/projects/ranchi.jpg",
    ProjectsLoveHotelBali : "/media/images/projects/love-hotel-bali.jpg",
    ProjectsBaliVilla : "/media/images/projects/bali.jpg",
    ProjectsPuneTathawade : "/media/images/projects/F-Residence-Tathawade-Pune.jpg",
    ProjectsPunePaud : "/media/images/projects/F-Villas-Paud-Pune.jpg",
    ProjectsKolkataUpComing : "/media/images/projects/kolkata-upcoming.jpg",
    // ProjectsPolandCommerical : "/media/images/projects/poland-commercial.jpg",
    MaladBannerImg : "/media/images/projects/project-image-1.webp",
    LicenseIndustry : "/media/images/Pre-requisites-Licence_industry_attraction.png",
    StrongDesire : "/media/images/Pre-requisites-Strong_desire_to_be_more.png",
    BrandSupport : "/media/images/brand-support.webp",
    ctapost : "/media/images/ctabaen.webp",
    vision : "/media/images/vision.webp",
    Aim : "/media/images/Aim.webp",
    Mission : "/media/images/Mission.webp",
    verticalIntro : "/media/images/verticalIntro.webp",
    Img1 : "/media/images/img-1.webp",
    // blognew : "/media/images/blogs/blognew.jpeg",
    // blognewbanner : "/media/images/blogs/blognewbanner.jpeg",
    // blogimage2 : "/media/images/blogs/blogimage2.jpeg",
    // blogimage4 : "/media/images/blogs/blogimage3.jpeg",
    // blogimage6 : "/media/images/blogs/blogimage6.jpeg",
    // blognewbanner002 : "/media/images/blogs/blognewbanner002.jpeg",
    // blognewbanner2 : "/media/images/blogs/blognewbanner2.jpeg",
    // blogimage3 : "/media/images/blogs/blogimag2banner.jpeg",
    // BlogImg1 : "/media/images/blogs/designing-the-perfect-home-office-thumbnail.png",
    // BlogImg2 : "/media/images/blogs/designing-for-Multigenerational-Living-thumbnail.png",
    // BlogImg3 : "/media/images/blogs/beyond-traditional-investments-thumbnail.png",
    // BlogImg4 : "/media/images/blogs/how-fashion-and-real-estate-industries-are-collaborating-thumbnail.png",
    // BlogImg5 : "/media/images/blogs/get-your-trendy-home-thumbnail.png",
    // BlogImg6 : "/media/images/blogs/luxury-amenities-what-today-high-end-thumbnail.png",
    // BlogImg7 : "/media/images/blogs/the-future-of-luxury-real-estate-in-india-thumbnail.png",
    // BlogImg8 : "/media/images/blogs/the-emergence-of-coworking-spaces-in-india-thumbnail.png",
    // BlogImg9 : "/media/images/blogs/the-millennial-homebuyer-thumbnail.png",
    // BlogImg10 : "/media/images/blogs/The-Role-of-Real-Estate-Agents-humbail.png",
    ctaBanner : "/media/images/cta-image.png",
    // banner1:"/media/images/banner1.webp",
    // banner2:"/media/images/banner2.webp",
    // banner3:"/media/images/banner3.webp",
    // banner4:"/media/images/banner4.webp",
    // banner5:"/media/images/banner5.webp",
    // banner6:"/media/images/banner6.webp",
    // banner7:"/media/images/banner7.webp",
    // banner8:"/media/images/banner8.webp",
    // banner9:"/media/images/banner9.webp",
    // banner10:"/media/images/banner10.webp",
    bgDiaBottom:"/media/images/bg-dia-bottom.png",
    bgDiaTop:"/media/images/bg-dia-top.png",
    licenseOpp:"/media/images/license-opportunity.jpg",

    // KK
    kkImg: "/media/images/kashiff-khan.jpeg",
    kkBannerImg: "/media/images/kashiff-khan-banner-img.jpg",
    // kkImg1: "/media/images/kashiffkhan.jpg",
    kkImg2: "/media/images/kashi-khan-img2.jpg",
    // kkworkImg: "/media/images/kkwork.png",
    kkworkImg: "/media/images/kkwork.jpeg",
    // MA
    maImg: "/media/images/miche-adam.jpeg",
    // maBannerImg: "/media/images/ma-banner.png",
    maBannerImg: "/media/images/ma-banner.jpeg",
    maIntro: "/media/images/maintro.png",
    ma3: "/media/images/ma-3.png",
}

export default AllImages;

